/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.7.0] */
/* PROTOCOL [CAN] */
/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h> 
/* End BUSMASTER include header */
/* Start BUSMASTER global variable */
/* End BUSMASTER global variable */
/* Start BUSMASTER Function Prototype */
GCC_EXTERN void GCC_EXPORT OnMsg_All(STCAN_MSG RxMsg);
GCC_EXTERN void GCC_EXPORT OnError_Warning_Limit(SCAN_ERR ErrorMsg);
GCC_EXTERN void GCC_EXPORT OnDLL_Load();
GCC_EXTERN void GCC_EXPORT OnDLL_Unload();
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
GCC_EXTERN void GCC_EXPORT OnBus_Disconnect();
GCC_EXTERN void GCC_EXPORT OnMsgID_7F0(STCAN_MSG RxMsg);
GCC_EXTERN void GCC_EXPORT OnTimer_timeout_5000( );
/* End BUSMASTER Function Prototype */

int seed_sent_flag=0;
int timeout_flag=0;
int seed = 0xFEEDBEEF;
int key=0;
STCAN_MSG TxMsg;
STCAN_MSG RxMsg;
int flag;

void print_stuff(RxMsg.m_unMsgID, int Time, RxMsg.m_sWhichBit.m_aucData[0], RxMsg.m_sWhichBit.m_aucData[1], RxMsg.m_sWhichBit.m_aucData[2], RxMsg.m_sWhichBit.m_aucData[3], RxMsg.m_sWhichBit.m_aucData[4], RxMsg.m_sWhichBit.m_aucData[5], RxMsg.m_sWhichBit.m_aucData[6], RxMsg.m_sWhichBit.m_aucData[7], RxMsg.m_sWhichBit.m_aucData[8] RxMsg.m_sWhichBit.m_aucData[9]) {
	Trace("%d, RxMsg.m_unMsgID);
	Trace();
		Trace("%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n", RxMsg.m_sWhichBit.m_aucData[0], RxMsg.m_sWhichBit.m_aucData[1], RxMsg.m_sWhichBit.m_aucData[2], RxMsg.m_sWhichBit.m_aucData[3], RxMsg.m_sWhichBit.m_aucData[4], RxMsg.m_sWhichBit.m_aucData[5], RxMsg.m_sWhichBit.m_aucData[6], RxMsg.m_sWhichBit.m_aucData[7], RxMsg.m_sWhichBit.m_aucData[8] RxMsg.m_sWhichBit.m_aucData[9]);
}

void _First_Message_Sniff_RxMsg(STCAN_MSG RxMsg){
	
	if RxMsg.m_unMsgID = 0x10A){flag = 1;}
	if RxMsg.m_unMsgID = 0x10B){flag = 2;}
	if RxMsg.m_unMsgID = 0x3AE){flag = 3;}
	if RxMsg.m_unMsgID = 0x444){flag = 4;}
	if RxMsg.m_unMsgID = 0x105){flag = 5;}
	if RxMsg.m_unMsgID = 0x555){flag = 6;}
	if RxMsg.m_unMsgID = 0x322){flag = 7;}
	if RxMsg.m_unMsgID = 0x211){flag = 8;}
	if RxMsg.m_unMsgID = 0x169){flag = 9;}
}



void Message_Sniff_RxMsg(STCAN_MSG RxMsg){
	if RxMsg.m_unMsgID = 0x10A){flag = 1;}
	if RxMsg.m_unMsgID = 0x10B){flag = 2;}
	if RxMsg.m_unMsgID = 0x3AE){flag = 3;}
	if RxMsg.m_unMsgID = 0x444){flag = 4;}
	if RxMsg.m_unMsgID = 0x105){flag = 5;}
	if RxMsg.m_unMsgID = 0x555){flag = 6;}
	if RxMsg.m_unMsgID = 0x322){flag = 7;}
	if RxMsg.m_unMsgID = 0x211){flag = 8;}
	if RxMsg.m_unMsgID = 0x169){flag = 9;}
}



/*一番目と二番目の関数でclock()をするつもりだった*/
	